# Generated by Django 5.2.6 on 2025-09-07 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='livestock',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='livestock',
            name='health_status',
            field=models.CharField(default='Healthy', max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='species',
            field=models.CharField(default='', max_length=100),
        ),
    ]
