# Generated by Django 5.2.6 on 2025-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
