# Generated by Django 5.0.13 on 2025-09-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock')),
            ],
        ),
    ]
