# Generated by Django 5.0.13 on 2025-09-07 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='harvest_date',
        ),
        migrations.AddField(
            model_name='crop',
            name='variety',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planting_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
