# Generated by Django 5.2.6 on 2025-09-07 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_remove_crop_harvest_date_crop_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='estimated_harvest_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.CharField(default='', max_length=100),
        ),
    ]
